### ISSUE TITLE
Submit to the ZAP Marketplace

### ISSUE THREAD

**Issue by psiinon** [secdec/attack-surface-detector-zap#1]
Thanks for developing this :)
Would you like it added to the ZAP Marketplace so that people can install it from within ZAP? https://github.com/zaproxy/zap-extensions
If so just raise a https://github.com/zaproxy/zaproxy issue and we'll review it asap.

**Comment by matthewD-AVI** [comment]
I raised the issue to get the plugin in the Marketplace. Hopefully we hear from you all soon

**Comment by psiinon** [comment]
Yes, saw that, and many thanks :)
We have a few suggestions which we'll add to that issue soon.
