### ISSUE TITLE
Version mismatch in add-on manifest

### ISSUE THREAD

**Issue by thc202** [secdec/attack-surface-detector-zap#16]
The filename says version 1.1.1 [1] but in the add-on manifest it is 1.1.0. [2]
The version in the manifest takes precedence.

I'd suggest setting that when building, similar to https://github.com/h3xstream/burp-retire-js/pull/22/files
(In this case it could set the version, status, and not-before-version.)

[1] https://github.com/secdec/attack-surface-detector-zap/releases/tag/1.1.1
[2] https://github.com/secdec/attack-surface-detector-zap/blob/1.1.1/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L3

**Comment by matthewD-AVI** [comment]
Resolving this issue right away

**Comment by matthewD-AVI** [comment]
issue is resolved as of commit 065d504f32571ebb9ca01440dbea47f9c6c3c49a

**Comment by thc202** [comment]
Thanks for the quick turnaround!
