### ISSUE TITLE
Update Installation wiki page to mention marketplace

### ISSUE THREAD

**Issue by thc202** [secdec/attack-surface-detector-zap#17]
Per release of the add-on to marketplace (zaproxy/zaproxy#4670) the [Installation wiki page](https://github.com/secdec/attack-surface-detector-zap/wiki/Installation) could also mention the marketplace.

**Comment by matthewD-AVI** [comment]
I'll take care of it right away

**Comment by matthewD-AVI** [comment]
Sorry for the delay. The wiki has been updated. 
https://github.com/secdec/attack-surface-detector-zap/wiki/Installation

**Comment by thc202** [comment]
Thanks!
