### ISSUE TITLE
attack-surface-detector-zap automation with python3

### ISSUE THREAD

**Issue by Jihane-H** [secdec/attack-surface-detector-zap#18]
Hi,

As part of my final year project, I'm working on a project where I need to automate security testing with ZAP and specially automate the identification of the entry points of a Web application using the plugin "Surface Attack Detector". I need help in automating the use of the plugin of zap via the command line interface so I can integrate it in my python3 scripts, and that without the need of using Docker knowing that I am already working with Kali machine.

Looking forward for your response.

Thank you in advance for your help and collaboration.

Jihane

**Comment by matthewD-AVI** [comment]
Hello Jihane, I am very glad you are interested in using ASD and potentially expanding upon it for your final project. I would be very interested in talking to you to gather some extra information. My email is Matthew.deletto@securedecisions.com please contact me.

**Comment by matthewD-AVI** [comment]
Hello Jihane, I am not sure if you are aware but there is a command line version of the Attack Surface Detector. The CLI tool is can be pointed at directory of code and then output the endpoints discovered from that application. If you were to write a python script that utilizes the ASD-CLI tool to generate a json output of endpoints and then use a json parser in your python script to retrieve all of the endpoints and their corresponding parameters. I hope you have found this helpful, and if you need any clarification please let me know.
