### ISSUE TITLE
Usage via ZAP REST API?

### ISSUE THREAD

**Issue by chasemh** [secdec/attack-surface-detector-zap#22]
Hello,

I'm interested in using the ASD extension for ZAP. However, I usually use ZAP in headless mode and interact with ZAP via the exposed REST API. What I would like to be able to do with this extension is take an endpoint JSON file that was generated via the attack-surface-detector-cli and then send that JSON to ZAP via a REST endpoint. Is this possible currently? I've looked through the documentation wiki but I've only seen documentation on configuring the ASD plugin via the ZAP GUI.

I noticed issue #18 as well. I'm not sure if anything came out of that issue outside of the issue thread, but I'm also using Python 3 to interact with the ZAP API.

Thanks in advance for your help.

**Comment by hoodoer** [comment]
I don't want to speak for the developer here, but I suspect you can't do that. 

What you could easily do is take the JSON output from the cli tool and use the ZAP rest API to make requests to those endpoints with those parameters. That's essentially what the ASD plugin does to get the endpoints and parameters into the target site map.

**Comment by matthewD-AVI** [comment]
@chasemh hoodoer is completely correct. Currently there is no support for use  of ASD with ZAP in headless mode but you could parse the information in the JSON output and make requests based on the parameter information discovered during the static analysis.

**Comment by chasemh** [comment]
Thank you both for the timely response. I'll look into parsing out the URLs from the JSON file and importing them outside of the ASD plugin.

I noticed a note in the OWASP ASD roadmap on extending ASD for headless usage eventually. Is there any current timeline on when that functionality might be added?

**Comment by matthewD-AVI** [comment]
@chasemh Unfortunately while headless usage is in the roadmap there is currently no timeline for completion.

**Comment by chasemh** [comment]
@matthewD-AVI Thanks for the response. I'll go ahead and close out this issue then.
