### ISSUE TITLE
how to install into headless zap?

### ISSUE THREAD

**Issue by dogasantos** [secdec/attack-surface-detector-zap#24]
./zap.sh -cmd -addoninstall <what?>
Not planning to use gui version at all. There is no way to know the plugin name/ID on the internet.
Can you please give us (headless users) a hand?
Thanks

**Comment by thc202** [comment]
You should use `attacksurfacedetector`, that's shown in the Manage Add-ons dialogue in ZAP.

We'll update https://www.zaproxy.org/addons/ to also show the IDs of the add-ons.

**Comment by dogasantos** [comment]
yeap, i've tried. But attacksurfacedetector does not work for me as well.
But thanks!

**Comment by thc202** [comment]
That's the ID of the add-on: https://github.com/zaproxy/zap-admin/blob/95128be09e39e4fb4b82b3fcc82feedb9198ff8d/ZapVersions-2.10.xml#L245

Maybe there's other problem than the ID.

**Comment by dogasantos** [comment]
Hey!
I found more issues going on with my Zap, so I've removed the entire program and cloned a new one.
Now, the install is working as it should:

```
./zap.sh -cmd -addoninstall attacksurfacedetector
...
Add-on downloaded to: /root/.ZAP/plugin/attacksurfacedetector-alpha-1.1.4.zap
```

Thanks !!
