### ISSUE TITLE
NPE when threadfix.properties not cleaned up

### ISSUE THREAD

**Issue by kingthorin** [secdec/attack-surface-detector-zap#3]
I pointed it at a *.war which I guess isn't an option it can handle. Even after removing and re-installing the addon I couldn't get it to action the menu item without a Null Pointer Exception.

> 36324 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - About to show dialog.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning useHttps false
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPath 
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPort 8090
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetHost localhost
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder C:\Users\thorin\Downloads\xampp-portable-win32-5.6.23-0-VC11\xampp\tomcat\webapps\bodgeit.war
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder C:\Users\thorin\Downloads\xampp-portable-win32-5.6.23-0-VC11\xampp\tomcat\webapps\bodgeit.war
> 36324 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - configured
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36324 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder C:\Users\thorin\Downloads\xampp-portable-win32-5.6.23-0-VC11\xampp\tomcat\webapps\bodgeit.war
> 36324 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - Got source information, about to generate endpoints.
> 36629 [AWT-EventQueue-0] INFO FrameworkCalculator  - Attempting to guess Framework Type from source tree.
> 36629 [AWT-EventQueue-0] INFO FrameworkCalculator  - File: C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\tomcat\\webapps\\bodgeit.war
> 36629 [AWT-EventQueue-0] WARN FrameworkCalculator  - Invalid directory passed to FrameworkCalculator.getType(File): C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\tomcat\\webapps\\bodgeit.war
> 36629 [AWT-EventQueue-0] INFO FrameworkCalculator  - Source tree framework type detection returned: None
> 36629 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Creating database with root file = C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\tomcat\\webapps\\bodgeit.war and framework type = NONE and path cleaner = [PathCleaner dynamicRoot=null, staticRoot=null]
> 36629 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Returning database with generator (null): null
> 36629 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 36629 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 36629 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder null
> 36629 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
> java.lang.NullPointerException
> 	at com.securedecisions.attacksurfacedetector.plugin.zap.action.EndpointsAction$1.actionPerformed(EndpointsAction.java:70)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
> 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2238)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2296)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2282)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 162116 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - About to show dialog.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Creating new file.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning useHttps null
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPath null
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPort null
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetHost null
> 162116 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.dialog.OptionsDialog  - Attempting to show dialog.
> 162116 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning useHttps null
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning autospider null
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder null
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder null
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetHost null
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPort null
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 162131 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPath null
> 

After manually removing threadfix.properties things started working again.

**Comment by matthewD-AVI** [comment]
I see that does seem to be a problem. I will be looking into it right away but I could use some clarification. When you say " I couldn't get it to action the menu item" is that the import endpoints menu button in the tools tab? Did you try and open the options dialog and change the source code location? If so did opening the options dialog also cause the Null Pointer Exception?

**Comment by kingthorin** [comment]
The menu item worked once (displayed the options dialog), I clicked ok and nothing happened. Then wouldn't display the options dialog again until I removed the file. When I checked the log on subsequent clicks of the menu item I saw the NPE.

_Edit_: @matthewD-AVI I'd be happy to submit or assist with the solution. I just didn't have time to dig into this before work when I was testing it. I looked at the code quickly and didn't see anything obvious. If it's a quick thing that you see because you're familiar with the code then cool. If not, then if you have a few tips I can try to look into it at lunch or this evening.

**Comment by matthewD-AVI** [comment]
I will look into and of course you are free to as well. I just want to make sure that I fully understand what is happening. If I understand your issue correctly you are receiving a npe but the program is not crtashing correct? You should be seeing this dialog when trying to import from a .war

![image](https://user-images.githubusercontent.com/35819157/39759669-466e3bf0-52a1-11e8-8912-132d97dfc5cf.png)


The properties file is designed to not be cleared so that the configurations can persist through versions and session. Also the options dialog is designed to not show when selecting "Import endpoints from Source" when all required options are given. these can be changed by manually opening the options dialog. through the status pane located here.

![image](https://user-images.githubusercontent.com/35819157/39759914-eef3cb78-52a1-11e8-8080-fb57fbd9b1f2.png)


Opening the tab should have a button labeled options. which should show the following dialog.
![image](https://user-images.githubusercontent.com/35819157/39759969-0cdd2792-52a2-11e8-96d1-2ab041e489af.png)

As you can see I did all of this after configuring the plugin to import from a .war file and this was done after trying to import. Have you followed these steps? If you select the options button does the options dialog fail to show? if so can I see a screen shot of the options button and then what happens when the options dialog fails to load?

**Comment by kingthorin** [comment]
No the program doesn't crash. It just does nothing (on subsequent tries) and I see the NPE in the logs. The warning dialog you mentioned doesn't display.

I didn't even look for the other tab and functionality, I only got as far as the Tools menu item then hit these few issues and had to leave for work :(

I'll use it some more at lunch and see where I can get with it.

**Comment by matthewD-AVI** [comment]
I see, I would like to see if you are able to open the options dialog, if so I don't see this much as a bug in fact this was the desired functionality so that the user does not have to configure every time they do another import. I will discuss having the dialog show from the tools menu, but I am not sure if it defeats the purpose of the options dialog. If you are able to reconfigure through the options dialog then this issue can most likely be resolved as commit #6916ef1 should resolve the NPE

**Comment by matthewD-AVI** [comment]
The user has the option to open the options dialog through the status window for the Attack Surface Difference generator to reconfigure the attack properties. The properties will still persist through sessions. The NPE will no longer be thrown when the plugin is given an unsupported framework and only valid file formats are now selectable. This issue has been resolved https://github.com/secdec/attack-surface-detector-zap/commit/5d0e946e76b77d75fc508bf505edded504e33c49

**Comment by kingthorin** [comment]
Thanks @matthewD-AVI I'll try it out sometime this week.
