### ISSUE TITLE
NPE importing php app (or JSP content)

### ISSUE THREAD

**Issue by kingthorin** [secdec/attack-surface-detector-zap#4]
Yes I realize now that PHP isn't on the list https://github.com/secdec/attack-surface-detector-zap#supported-frameworks, but it's probably a condition that should be handled.

I tried importing mutillidae and encountered an NPE.

> 471150 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471166 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471181 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - configured
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 471181 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder C:\Users\thorin\Downloads\xampp-portable-win32-5.6.23-0-VC11\xampp\htdocs\mutillidae
> 471181 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - Got source information, about to generate endpoints.
> 471181 [AWT-EventQueue-0] INFO FrameworkCalculator  - Attempting to guess Framework Type from source tree.
> 471181 [AWT-EventQueue-0] INFO FrameworkCalculator  - File: C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\htdocs\\mutillidae
> 472851 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.dotNet.DotNetFrameworkChecker  - Got 0 .cs files from the directory.
> 473258 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.dotNet.DotNetFrameworkChecker  - Got 0 Controller files from the directory.
> 473648 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.dotNetWebForm.WebFormsFrameworkChecker  - Got 0 .aspx files from the directory.
> 474054 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.rails.RailsFrameworkChecker  - Got 0 *.rb files from the directory.
> 474054 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.rails.RailsFrameworkChecker  - .../config/routes.rb was NOT found.
> 474476 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.django.DjangoFrameworkChecker  - Got 0 .py files from the directory.
> 474476 [AWT-EventQueue-0] INFO FrameworkCalculator  - Source tree framework type detection returned: None
> 474476 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Creating database with root file = C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\htdocs\\mutillidae and framework type = NONE and path cleaner = [PathCleaner dynamicRoot=null, staticRoot=null]
> 474476 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Returning database with generator (null): null
> 474476 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 474491 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 474491 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder null
> 474491 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
> java.lang.NullPointerException
> 	at com.securedecisions.attacksurfacedetector.plugin.zap.action.EndpointsAction$1.actionPerformed(EndpointsAction.java:70)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
> 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2238)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2296)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2282)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I then thought ok, [delete the threadfix.properties file](https://github.com/secdec/attack-surface-detector-zap/issues/3), restart ZAP and just import some *.jsp that should be simple. NPE again and [it doesn't seem that JSP](https://github.com/secdec/attack-surface-detector-zap#supported-frameworks) was checked at all:

> 27499 [AWT-EventQueue-0] INFO FrameworkCalculator  - File: C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\tomcat\\webapps\\wavsep\\active
> 28919 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.dotNet.DotNetFrameworkChecker  - Got 0 .cs files from the directory.
> 29233 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.dotNet.DotNetFrameworkChecker  - Got 0 Controller files from the directory.
> 29592 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.dotNetWebForm.WebFormsFrameworkChecker  - Got 0 .aspx files from the directory.
> 29951 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.rails.RailsFrameworkChecker  - Got 0 *.rb files from the directory.
> 29951 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.rails.RailsFrameworkChecker  - .../config/routes.rb was NOT found.
> 30279 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.impl.django.DjangoFrameworkChecker  - Got 0 .py files from the directory.
> 30279 [AWT-EventQueue-0] INFO FrameworkCalculator  - Source tree framework type detection returned: None
> 30295 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Creating database with root file = C:\\Users\\thorin\\Downloads\\xampp-portable-win32-5.6.23-0-VC11\\xampp\\tomcat\\webapps\\wavsep\\active and framework type = NONE and path cleaner = [PathCleaner dynamicRoot=null, staticRoot=null]
> 30295 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Returning database with generator (null): null
> 30295 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at C:\Users\thorin\OWASP ZAP_D\threadfix.properties
> 30295 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
> 30295 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source code folder null
> 30295 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
> java.lang.NullPointerException
> 	at com.securedecisions.attacksurfacedetector.plugin.zap.action.EndpointsAction$1.actionPerformed(EndpointsAction.java:70)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
> 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2238)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2296)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2282)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 

Note around 29233 it mentions rb, cs, py, routes.rb, Controller, .aspx; but not [JSP](https://github.com/secdec/attack-surface-detector-zap#supported-frameworks)?

**Comment by tylercamp** [comment]
@matthewD-AVI Make sure you check that the EndpointGenerator isn't null when you go to generate endpoints; this can occur when the framework isn't detected

@kingthorin You're right, strangely the JSP detection logic is missing, I'll add it to the [ASTAM correlator repo](https://github.com/secdec/astam-correlator) which will require an update to the maven dependencies

**Comment by kingthorin** [comment]
Note this is from fresh install of the addon. Running the currently weekly D-2018-05-08, starting from zap.bat (so that the console is shown).

Ok, so the NPE only happens the first time when I try to import a war from the tools menu item. If I then try the tools menu item again nothing happens. (In fact it still show highlighted, which is weird.)

![image](https://user-images.githubusercontent.com/7570458/39762587-0726bdca-52a9-11e8-9d80-f2b3e0ccb53b.png)
Go back and click on the tools menu, the menu item is still shown selected.....weird!
![image](https://user-images.githubusercontent.com/7570458/39762800-955f43fa-52a9-11e8-846c-483c522cb215.png)

```
22999 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - Installing new addon attacksur
facedetector v1.0.0
23020 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.AttackSurfaceDetector  - Loading Class
23020 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.AttackSurfaceDetector  - calling construct
or
23020 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.AttackSurfaceDetector  - Initialize
23020 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.AttackSurfaceDetector  - No-arg Constructo
r
23026 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.AttackSurfaceDetector  - Hook
23027 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.AttackSurfaceDetector  - Getting menu
23029 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - Initia
lizing Attack Surface Detector menu item: "Attack Surface Detector: Import Endpoints from Source"
27626 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - About
to show dialog.
27631 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27632 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Creating new file.

27636 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27637 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning useHttps
 null
27637 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27639 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27640 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPa
th null
27641 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27643 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27643 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPo
rt null
27644 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27645 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27646 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetHo
st null
27647 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.dialog.OptionsDialog  - Attempting to
 show dialog.
27647 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27648 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27649 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning useHttps
 null
27649 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27650 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27650 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning autospid
er null
27662 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27663 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27663 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source c
ode folder null
27665 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27666 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27666 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source c
ode folder null
27667 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27668 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27669 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetHo
st null
27670 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27671 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27671 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPo
rt null
27672 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
27673 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
27673 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning targetPa
th null
68437 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68439 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68443 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68445 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68449 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68451 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68454 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68455 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68458 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68460 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68463 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68465 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68473 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - config
ured
68473 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68475 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68476 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source c
ode folder C:\Rick\ZAP_DEV\xampp\tomcat\webapps\docs\appdev\sample\sample.war
68476 [AWT-EventQueue-0] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsAction  - Got so
urce information, about to generate endpoints.
68491 [AWT-EventQueue-0] INFO FrameworkCalculator  - Attempting to guess Framework Type from source tree.
68492 [AWT-EventQueue-0] INFO FrameworkCalculator  - File: C:\\Rick\\ZAP_DEV\\xampp\\tomcat\\webapps\\docs\\appdev\\samp
le\\sample.war
68494 [AWT-EventQueue-0] WARN FrameworkCalculator  - Invalid directory passed to FrameworkCalculator.getType(File): C:\\
Rick\\ZAP_DEV\\xampp\\tomcat\\webapps\\docs\\appdev\\sample\\sample.war
68494 [AWT-EventQueue-0] INFO FrameworkCalculator  - Source tree framework type detection returned: None
68496 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Creating database with root file = C:\\Rick\\ZAP_DEV\\xampp\\to
mcat\\webapps\\docs\\appdev\\sample\\sample.war and framework type = NONE and path cleaner = [PathCleaner dynamicRoot=nu
ll, staticRoot=null]
68496 [AWT-EventQueue-0] INFO EndpointDatabaseFactory  - Returning database with generator (null): null
68496 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is
 at C:\Users\mitchr\OWASP ZAP_D\threadfix.properties
68498 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loade
d properties.
68498 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - returning source c
ode folder null
68499 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException
        at com.securedecisions.attacksurfacedetector.plugin.zap.action.EndpointsAction$1.actionPerformed(EndpointsAction
.java:70)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

At this point the tools menu item does nothing.

If I then goto the tab and hit "Options" and "ok" again then either the tools menu item or "Import Endpoints from Source" button will cause the warning dialog to display:
![image](https://user-images.githubusercontent.com/7570458/39762969-f238e392-52a9-11e8-81c7-d80e2430394c.png)
**Note**: When the warning happens, the NPE is not logged.

I think it makes sense for users to expect that warning to display after clicking "Ok" on the Options dialog... In fact maybe if it isn't successful (the warning displayed) it should just re-pop the Options dialog?

I could then go back into the Options dialog and clear all the values and hit ok. Then "Import Endpoints from Source" or the tools menu item open the Options dialog as expected once again.

**Comment by kingthorin** [comment]
Now that I’ve used it a bit more and you’ve made me aware of the tab I think #3 and #4 are likely duplicates (same or nearly same cause).

**Comment by matthewD-AVI** [comment]
@tylercamp has added back the jsp support, and .War support but those changes are waiting on maven . I made a commit that should fix the NPE issue you were seeing.

**Comment by kingthorin** [comment]
Any news on the changes making their way through maven?

**Comment by matthewD-AVI** [comment]
changes to add .war support are in maven now and will be added to the plugins hopefully today. .war support is only for war files that contain source code since the engine actually comes the source code itself. jsp support has returned and both plugins now only allow the user to select accepted file formats or directories. The NPE has been resolved ass well and I will be closing both issues.

**Comment by matthewD-AVI** [comment]
https://github.com/secdec/attack-surface-detector-zap/commit/5d0e946e76b77d75fc508bf505edded504e33c49

**Comment by kingthorin** [comment]
I can pull the code and build it, however, for the community etc will 1.11 (or whatever) be published soon?
https://github.com/secdec/attack-surface-detector-zap/releases

**Comment by matthewD-AVI** [comment]
@kingthorin  A few other minor changes are being implemented and once properly Testing I will be drafting a new release hopefully sometime this week

**Comment by kingthorin** [comment]
Great, thanks! :+1:

**Comment by kingthorin** [comment]
Just to close the loop on this I was able to successfully import a directory of jsp files.
